import { Box, CssBaseline } from '@mui/material'
import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import SearchAppBar from '../components/SearchAppBar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const MapWithNoSSR = dynamic(() => import("../components/Map"), {
    ssr: false
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
          <CssBaseline />
          <SearchAppBar />
          <Box sx={{ flexGrow: 1, display: 'flex' }} >
            <Box sx={{ flexGrow: 1 }}>
              <MapWithNoSSR />
            </Box>
          </Box>
        </Box>
      </main>
    </div>
  )
}

export default Home
